spring.application.name=Week02HomeWork
spring.datasource.url=jdbc:h2:file:./data/departmentDB
spring.datasource.username=sa
spring.datasource.password=password


spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true