spring.application.name=SpringBootWebApplication

#this allows us to save the data inside the file instead of inMemory.
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/H2DB
spring.datasource.username=saheelDB
spring.datasource.password=saheel123
#spring.jpa.hibernate.ddl-auto=create  #do this first time
spring.jpa.hibernate.ddl-auto=create-drop